# Generated by Django 5.1.1 on 2025-06-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.FloatField(blank=True, help_text='上傳者評分，可不填', null=True),
        ),
    ]
