# Generated by Django 5.1.1 on 2025-06-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='rate_posta',
        ),
        migrations.AddField(
            model_name='comment',
            name='rate_comment',
            field=models.PositiveSmallIntegerField(blank=True, help_text='留言評分，可不填', null=True),
        ),
    ]
