# Generated by Django 5.1.1 on 2025-06-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_is_approved_post_is_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='軟刪除：被刪除則不顯示於前台'),
        ),
    ]
