# Generated by Django 5.1.1 on 2025-06-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='report_time',
            field=models.DateTimeField(blank=True, help_text='檢舉時間', null=True),
        ),
    ]
