# Generated by Django 5.1.1 on 2025-06-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_rating_post_rate_posta_comment_rate_comment'),
        ('posts', '0007_favorite'),
    ]

    operations = [
    ]
