# Generated by Django 5.1.1 on 2025-06-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_category_category_type_category_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='location_type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=20),
        ),
    ]
