# Generated by Django 5.1.1 on 2025-06-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_category_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='location_type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=10),
        ),
    ]
