# Generated by Django 5.1.1 on 2025-06-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_category_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='want_email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
