# Generated by Django 5.1.1 on 2025-06-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_post_is_approved_post_is_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='location_type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=20),
        ),
    ]
